import { IReportBranding } from './ReportTypes';

export class ReportBrandingEngine {
  private static instance: ReportBrandingEngine;

  private defaultBranding: IReportBranding = {
    brandingId: 'brand-urjaflux-default',
    companyName: 'URJAFLUX AI OS Enterprise Solutions',
    tagline: 'Quantum-Spatial Architecture & Bio-Resonant Diagnostic Intelligence',
    primaryColor: '#0f766e', // Emerald 700
    secondaryColor: '#1e293b', // Slate 800
    accentColor: '#d97706', // Amber 600
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    clientLogoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&auto=format&fit=crop&q=80',
    headerText: 'URJAFLUX Enterprise Intelligence - Strict Verification & Compliance Record',
    footerText: 'Confidential Document • Generated by URJAFLUX AI OS • Validated by Canonical Sthapatya & Bio-Energy Engine',
    watermarkText: 'VERIFIED REPORT • URJAFLUX AI OS',
    fontFamily: 'Inter',
    showQrCode: true,
    qrCodeTargetUrl: 'https://urjaflux.ai/verify/doc-88291'
  };

  private constructor() {}

  public static getInstance(): ReportBrandingEngine {
    if (!ReportBrandingEngine.instance) {
      ReportBrandingEngine.instance = new ReportBrandingEngine();
    }
    return ReportBrandingEngine.instance;
  }

  public getDefaultBranding(): IReportBranding {
    return { ...this.defaultBranding };
  }

  public getPresetThemes(): { id: string; name: string; branding: Partial<IReportBranding> }[] {
    return [
      {
        id: 'theme-royal-emerald',
        name: 'Royal Emerald (Canonical Vastu)',
        branding: {
          primaryColor: '#059669',
          secondaryColor: '#0f172a',
          accentColor: '#d97706',
          fontFamily: 'Plus Jakarta Sans'
        }
      },
      {
        id: 'theme-suryavanshi-gold',
        name: 'Suryavanshi Amber (Astro-Solar)',
        branding: {
          primaryColor: '#b45309',
          secondaryColor: '#1c1917',
          accentColor: '#eab308',
          fontFamily: 'Playfair Display'
        }
      },
      {
        id: 'theme-digital-twin-slate',
        name: 'Digital Twin Cobalt (Engineering)',
        branding: {
          primaryColor: '#0284c7',
          secondaryColor: '#0f172a',
          accentColor: '#10b981',
          fontFamily: 'Inter'
        }
      },
      {
        id: 'theme-minimalist-monochrome',
        name: 'Executive Minimalist (Client Presentation)',
        branding: {
          primaryColor: '#18181b',
          secondaryColor: '#3f3f46',
          accentColor: '#475569',
          fontFamily: 'Inter'
        }
      }
    ];
  }

  public applyCustomTheme(
    baseBranding: IReportBranding,
    overrides: Partial<IReportBranding>
  ): IReportBranding {
    return {
      ...baseBranding,
      ...overrides
    };
  }
}
