import {
  ILalKitabOntologyEntity,
  ILalKitabRelationship,
  ILalKitabConflict,
  ILalKitabDuplicateMatch
} from './LalKitabKnowledgeTypes';

export const INITIAL_LALKITAB_ENTITIES: ILalKitabOntologyEntity[] = [
  // ----------------------------------------------------
  // PLANETS (GRAHAS)
  // ----------------------------------------------------
  {
    id: 'lk-grh-001',
    canonicalName: 'Surya (Sun / Khurshid)',
    alternateNames: ['Aftab', 'Sun', 'Aditya', 'Ravi', 'Khurshid'],
    hindiName: 'सूर्य (Surya)',
    englishName: 'Sun',
    urduName: 'خورشید (Khurshid)',
    entityType: 'Graha',
    description: 'Master of soul, royalty, government, state authority, father, bone structure, and vital warmth in Lal Kitab shastra.',
    category: 'Graha Canon',
    tags: ['Graha', 'Sun', 'Royal', 'Father', 'Copper', 'Jaggery', 'East'],
    metadata: {
      exaltationHouse: 1,
      debilitationHouse: 7,
      pakkaGhar: 1,
      karka: 'Soul, Father, Royal Authority',
      friendlyPlanets: ['Guru', 'Chandra', 'Mangal'],
      enemyPlanets: ['Shani', 'Rahu', 'Ketu', 'Venus'],
      neutralPlanets: ['Budh']
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-001',
    associatedDirection: 'East',
    associatedRoom: 'Courtyard / Center-East Hall',
    associatedMetal: 'Copper',
    associatedColor: 'Crimson Red / Copper Amber',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 1 - Surya Graha Swaroop',
      pageNumber: 24,
      paragraph: 'Para 1, Verse 4-8',
      ocrConfidence: 0.99,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 98,
      evidenceStrength: 95,
      knowledgeWeight: 0.95,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import from Lal Kitab 1952 Farman']
  },
  {
    id: 'lk-grh-002',
    canonicalName: 'Chandra (Moon / Qamar)',
    alternateNames: ['Qamar', 'Moon', 'Soma', 'Chanda'],
    hindiName: 'चन्द्रमा (Chandra)',
    englishName: 'Moon',
    urduName: 'قمر (Qamar)',
    entityType: 'Graha',
    description: 'Significator of mind, mother, emotional peace, pure water, liquid wealth, silver, and maternal ancestors in Lal Kitab.',
    category: 'Graha Canon',
    tags: ['Graha', 'Moon', 'Mind', 'Mother', 'Silver', 'Milk', 'North-West'],
    metadata: {
      exaltationHouse: 2,
      debilitationHouse: 8,
      pakkaGhar: 4,
      karka: 'Mind, Mother, Liquid Cash, Water Sources',
      friendlyPlanets: ['Surya', 'Guru', 'Budh'],
      enemyPlanets: ['Rahu', 'Ketu'],
      neutralPlanets: ['Mangal', 'Shukra', 'Shani']
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-002',
    associatedDirection: 'North-West',
    associatedRoom: 'Water Storage / NW Dining Area',
    associatedMetal: 'Solid Silver',
    associatedColor: 'Pearl White / Milky Silver',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 2 - Chandra Graha Farman',
      pageNumber: 52,
      paragraph: 'Para 3, Verse 10',
      ocrConfidence: 0.98,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 96,
      evidenceStrength: 94,
      knowledgeWeight: 0.94,
      confidenceScore: 96,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import from Lal Kitab 1952 Farman']
  },
  {
    id: 'lk-grh-003',
    canonicalName: 'Mangal (Mars / Mreikh)',
    alternateNames: ['Mreikh', 'Mars', 'Angaraka', 'Kuja'],
    hindiName: 'मंगल (Mangal)',
    englishName: 'Mars',
    urduName: 'مریخ (Mreikh)',
    entityType: 'Graha',
    description: 'Significator of physical energy, courage, brothers, blood circulation, fire elements, and land property. Expresses as Mangal Badd or Mangal Neek.',
    category: 'Graha Canon',
    tags: ['Graha', 'Mars', 'Courage', 'Brothers', 'Copper', 'Red Sweet', 'South'],
    metadata: {
      exaltationHouse: 10,
      debilitationHouse: 4,
      pakkaGhar: 3,
      karka: 'Brothers, Courage, Property, Physical Energy',
      mangalNeekConditions: 'In beneficial houses with Surya/Guru',
      mangalBaddConditions: 'In 4th or 8th house without benefic aspects'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-003',
    associatedDirection: 'South',
    associatedRoom: 'Kitchen / Hearth',
    associatedMetal: 'Copper / Red Brass',
    associatedColor: 'Deep Crimson Red',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 3 - Mangal Farman',
      pageNumber: 78,
      paragraph: 'Para 2, Verse 15',
      ocrConfidence: 0.97,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 97,
      evidenceStrength: 92,
      knowledgeWeight: 0.92,
      confidenceScore: 95,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import from Lal Kitab 1952 Farman']
  },
  {
    id: 'lk-grh-004',
    canonicalName: 'Budh (Mercury / Utared)',
    alternateNames: ['Utared', 'Mercury', 'Budha', 'Soumya'],
    hindiName: 'बुध (Budh)',
    englishName: 'Mercury',
    urduName: 'عطارد (Utared)',
    entityType: 'Graha',
    description: 'Master of intellect, speech, trade, green vegetation, daughters, sisters, and hollow round objects. Known as the chameleon planet in Lal Kitab.',
    category: 'Graha Canon',
    tags: ['Graha', 'Mercury', 'Intellect', 'Trade', 'Bronze', 'Moong', 'North'],
    metadata: {
      exaltationHouse: 6,
      debilitationHouse: 12,
      pakkaGhar: 7,
      karka: 'Intellect, Business, Speech, Sisters, Daughters',
      chameleonNature: 'Takes nature of planet it sits with'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-004',
    associatedDirection: 'North',
    associatedRoom: 'Study Room / Library / Balcony',
    associatedMetal: 'Bronze / Brass Hollow Vessel',
    associatedColor: 'Emerald Green',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 4 - Budh Farman',
      pageNumber: 104,
      paragraph: 'Para 4, Verse 9',
      ocrConfidence: 0.99,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 99,
      evidenceStrength: 96,
      knowledgeWeight: 0.96,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import']
  },
  {
    id: 'lk-grh-005',
    canonicalName: 'Guru (Jupiter / Mushtari)',
    alternateNames: ['Mushtari', 'Jupiter', 'Brihaspati', 'Devaguru'],
    hindiName: 'गुरु (Guru / Brihaspati)',
    englishName: 'Jupiter',
    urduName: 'مشتری (Mushtari)',
    entityType: 'Graha',
    description: 'Significator of spiritual wisdom, fortune, grandfather, lineage, saffron, gold, and banyan tree. The supreme benefic of Lal Kitab.',
    category: 'Graha Canon',
    tags: ['Graha', 'Jupiter', 'Wisdom', 'Gold', 'Saffron', 'Gram Pulse', 'North-East'],
    metadata: {
      exaltationHouse: 4,
      debilitationHouse: 10,
      pakkaGhar: 2,
      karka: 'Wisdom, Dharma, Family Wealth, Grandfather'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-005',
    associatedDirection: 'North-East',
    associatedRoom: 'Pooja Room / Sacred Altar / NE Corner',
    associatedMetal: 'Gold / Brass',
    associatedColor: 'Golden Yellow / Turmeric Yellow',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 5 - Guru Farman',
      pageNumber: 130,
      paragraph: 'Para 1, Verse 1-5',
      ocrConfidence: 0.98,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 98,
      evidenceStrength: 97,
      knowledgeWeight: 0.97,
      confidenceScore: 99,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import']
  },
  {
    id: 'lk-grh-006',
    canonicalName: 'Shukra (Venus / Zohra)',
    alternateNames: ['Zohra', 'Venus', 'Shukracharya', 'Bhrigu'],
    hindiName: 'शुक्र (Shukra)',
    englishName: 'Venus',
    urduName: 'زهره (Zohra)',
    entityType: 'Graha',
    description: 'Significator of marital comfort, wife, aesthetic beauty, luxury vehicles, cows, white camphor, and refined arts.',
    category: 'Graha Canon',
    tags: ['Graha', 'Venus', 'Wife', 'Luxury', 'Curd', 'Camphor', 'South-East'],
    metadata: {
      exaltationHouse: 12,
      debilitationHouse: 6,
      pakkaGhar: 7,
      karka: 'Spouse, Material Wealth, Art, Vehicles'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-006',
    associatedDirection: 'South-East',
    associatedRoom: 'Primary Bedroom / Dressing Area',
    associatedMetal: 'Silver / White Gold',
    associatedColor: 'Snow White / Diamond Sparkle',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 6 - Shukra Farman',
      pageNumber: 156,
      paragraph: 'Para 2, Verse 8',
      ocrConfidence: 0.97,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 97,
      evidenceStrength: 95,
      knowledgeWeight: 0.95,
      confidenceScore: 97,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import']
  },
  {
    id: 'lk-grh-007',
    canonicalName: 'Shani (Saturn / Zuhal)',
    alternateNames: ['Zuhal', 'Saturn', 'Shanaishchar', 'Manda'],
    hindiName: 'शनि (Shani)',
    englishName: 'Saturn',
    urduName: 'زحل (Zuhal)',
    entityType: 'Graha',
    description: 'Significator of labor, justice, iron, black oil, old structures, dark storerooms, machinery, and perseverance.',
    category: 'Graha Canon',
    tags: ['Graha', 'Saturn', 'Justice', 'Labor', 'Iron', 'Mustard Oil', 'West'],
    metadata: {
      exaltationHouse: 7,
      debilitationHouse: 1,
      pakkaGhar: 8,
      karka: 'Longevity, Laborers, Real Estate, Machinery'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-007',
    associatedDirection: 'West',
    associatedRoom: 'Store Room / Dark Basement / West Wall',
    associatedMetal: 'Iron / Dark Steel',
    associatedColor: 'Jet Black / Navy Blue',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 7 - Shani Farman',
      pageNumber: 182,
      paragraph: 'Para 3, Verse 14',
      ocrConfidence: 0.98,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 98,
      evidenceStrength: 96,
      knowledgeWeight: 0.96,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import']
  },
  {
    id: 'lk-grh-008',
    canonicalName: 'Rahu (North Node / Dragon\'s Head)',
    alternateNames: ['Rahu', 'Dragon\'s Head', 'Tamah', 'Surabhanu'],
    hindiName: 'राहु (Rahu)',
    englishName: 'Rahu',
    urduName: 'راهو (Rahu)',
    entityType: 'Graha',
    description: 'Significator of sudden shocks, secrets, electricity, dark drains, smoke, blue color, elephant tusk, and in-laws.',
    category: 'Graha Canon',
    tags: ['Graha', 'Rahu', 'Electricity', 'Drains', 'Blue', 'Lead', 'South-West'],
    metadata: {
      exaltationHouse: 3,
      debilitationHouse: 9,
      pakkaGhar: 12,
      karka: 'In-laws, Electrical Wiring, Unexpected Events, Drains'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-008',
    associatedDirection: 'South-West',
    associatedRoom: 'Toilets / Sewer Drains / SW Threshold',
    associatedMetal: 'Lead / Raw Zinc',
    associatedColor: 'Smoky Blue / Charcoal Grey',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 8 - Rahu Farman',
      pageNumber: 210,
      paragraph: 'Para 1, Verse 9',
      ocrConfidence: 0.96,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 96,
      evidenceStrength: 92,
      knowledgeWeight: 0.92,
      confidenceScore: 94,
      confidenceGrade: 'A',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import']
  },
  {
    id: 'lk-grh-009',
    canonicalName: 'Ketu (South Node / Dragon\'s Tail)',
    alternateNames: ['Ketu', 'Dragon\'s Tail', 'Shikhi', 'Dhwaja'],
    hindiName: 'केतु (Ketu)',
    englishName: 'Ketu',
    urduName: 'کیتو (Ketu)',
    entityType: 'Graha',
    description: 'Significator of spiritual liberation, dogs, maternal grandfather, spine, joint pains, multi-color blankets, and flags.',
    category: 'Graha Canon',
    tags: ['Graha', 'Ketu', 'Spine', 'Dog', 'Blanket', 'Multi-color', 'North-East / Center'],
    metadata: {
      exaltationHouse: 9,
      debilitationHouse: 3,
      pakkaGhar: 6,
      karka: 'Spiritual Liberation, Dogs, Sons, Spine, Feet'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    planetId: 'lk-grh-009',
    associatedDirection: 'North-East',
    associatedRoom: 'Staircase Landing / Roof Apex',
    associatedMetal: 'Mixed Alloy / Alloy Silver-Gold',
    associatedColor: 'Two-Tone Black & White / Patterned',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 9 - Ketu Farman',
      pageNumber: 236,
      paragraph: 'Para 2, Verse 11',
      ocrConfidence: 0.97,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 97,
      evidenceStrength: 93,
      knowledgeWeight: 0.93,
      confidenceScore: 95,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Initial canonical import']
  },

  // ----------------------------------------------------
  // HOUSES (BHAVS 1 - 12)
  // ----------------------------------------------------
  {
    id: 'lk-bhv-001',
    canonicalName: 'Bhav 1 (First House / Tanu Bhav)',
    alternateNames: ['Pehla Ghar', 'House 1', 'Ascendant House', 'Tanu Bhav'],
    hindiName: 'प्रथम भाव (Bhav 1)',
    englishName: 'House 1',
    urduName: 'پہلا گھر (Pehla Ghar)',
    entityType: 'Bhav',
    description: 'Throne of the self, head, overall life force, physical vitality, main entrance, and royal seat in Lal Kitab. Pakka Ghar of Surya.',
    category: 'House Canon',
    tags: ['Bhav', 'House 1', 'Self', 'Head', 'Surya', 'Main Entrance', 'East'],
    metadata: {
      houseNumber: 1,
      pakkaGharPlanet: 'Surya',
      exaltedPlanet: 'Surya',
      debilitatedPlanet: 'Shani',
      bodyPart: 'Head & Brain',
      vastuZone: 'East / Entrance Porch'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    houseNumber: 1,
    associatedDirection: 'East',
    associatedRoom: 'Main Entrance Gate / Veranda',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Bhav Nirdesh - Pehla Ghar',
      pageNumber: 300,
      paragraph: 'Para 1, Verse 1',
      ocrConfidence: 0.99,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 99,
      evidenceStrength: 98,
      knowledgeWeight: 0.98,
      confidenceScore: 99,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical house definition']
  },
  {
    id: 'lk-bhv-002',
    canonicalName: 'Bhav 2 (Second House / Dhana Bhav)',
    alternateNames: ['Doosra Ghar', 'House 2', 'Dhana Bhav', 'Kutumba Bhav'],
    hindiName: 'द्वितीय भाव (Bhav 2)',
    englishName: 'House 2',
    urduName: 'دوسرا گھر (Doosra Ghar)',
    entityType: 'Bhav',
    description: 'Vault of accumulated wealth, family heritage, speech, throat, cash treasury, and indoor temple. Pakka Ghar of Guru.',
    category: 'House Canon',
    tags: ['Bhav', 'House 2', 'Wealth', 'Speech', 'Guru', 'Treasury', 'North-East'],
    metadata: {
      houseNumber: 2,
      pakkaGharPlanet: 'Guru',
      exaltedPlanet: 'Chandra',
      debilitatedPlanet: 'None',
      bodyPart: 'Face, Eyes & Throat',
      vastuZone: 'North-East / Puja Room'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    houseNumber: 2,
    associatedDirection: 'North-East',
    associatedRoom: 'Safe / Treasury / Puja Corner',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Bhav Nirdesh - Doosra Ghar',
      pageNumber: 312,
      paragraph: 'Para 2, Verse 4',
      ocrConfidence: 0.98,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 98,
      evidenceStrength: 96,
      knowledgeWeight: 0.96,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical house definition']
  },
  {
    id: 'lk-bhv-003',
    canonicalName: 'Bhav 3 (Third House / Bhati Bhav)',
    alternateNames: ['Teesra Ghar', 'House 3', 'Sahaja Bhav', 'Parakrama Bhav'],
    hindiName: 'तृतीय भाव (Bhav 3)',
    englishName: 'House 3',
    urduName: 'تیسرا گھر (Teesra Ghar)',
    entityType: 'Bhav',
    description: 'Arm of courage, younger siblings, neighbors, hands, writing, and martial strength. Pakka Ghar of Mangal.',
    category: 'House Canon',
    tags: ['Bhav', 'House 3', 'Courage', 'Siblings', 'Mangal', 'South'],
    metadata: {
      houseNumber: 3,
      pakkaGharPlanet: 'Mangal',
      exaltedPlanet: 'Rahu',
      debilitatedPlanet: 'Ketu',
      bodyPart: 'Arms & Shoulders',
      vastuZone: 'South-East / Gym / Martial Area'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    houseNumber: 3,
    associatedDirection: 'South-East',
    associatedRoom: 'Exercise Room / Balcony / Side Entrance',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Bhav Nirdesh - Teesra Ghar',
      pageNumber: 324,
      paragraph: 'Para 1, Verse 6',
      ocrConfidence: 0.97,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 97,
      evidenceStrength: 95,
      knowledgeWeight: 0.95,
      confidenceScore: 97,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical house definition']
  },
  {
    id: 'lk-bhv-004',
    canonicalName: 'Bhav 4 (Fourth House / Sukha Bhav)',
    alternateNames: ['Chautha Ghar', 'House 4', 'Matri Bhav', 'Sukha Bhav'],
    hindiName: 'चतुर्थ भाव (Bhav 4)',
    englishName: 'House 4',
    urduName: 'چوتھا گھر (Chautha Ghar)',
    entityType: 'Bhav',
    description: 'Nourishing sanctuary of mother, property, home foundation, peace of mind, water tanks, and wellsprings. Pakka Ghar of Chandra.',
    category: 'House Canon',
    tags: ['Bhav', 'House 4', 'Mother', 'Home', 'Chandra', 'Water Tank', 'North-West'],
    metadata: {
      houseNumber: 4,
      pakkaGharPlanet: 'Chandra',
      exaltedPlanet: 'Guru',
      debilitatedPlanet: 'Mangal',
      bodyPart: 'Chest & Lungs',
      vastuZone: 'North-West / Well / Underground Water'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    houseNumber: 4,
    associatedDirection: 'North-West',
    associatedRoom: 'Living Room / Water Sump / Central Courtyard',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Bhav Nirdesh - Chautha Ghar',
      pageNumber: 338,
      paragraph: 'Para 2, Verse 2',
      ocrConfidence: 0.99,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 99,
      evidenceStrength: 97,
      knowledgeWeight: 0.97,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical house definition']
  },

  // ----------------------------------------------------
  // REMEDIES (UPAYS)
  // ----------------------------------------------------
  {
    id: 'lk-rmd-001',
    canonicalName: 'Solid Silver Sphere in Water (Katha Chandi Upay)',
    alternateNames: ['Solid Silver Ball', 'Chandi Ka Gola', 'Silver in Silver Pot'],
    hindiName: 'ठोस चांदी का गोला जल में (Chandi Gola)',
    englishName: 'Solid Silver Sphere in Pure Water',
    urduName: 'ٹھوس چاندی کا گولا (Thos Chandi Gola)',
    entityType: 'Remedy',
    description: 'Placing a 40g pure solid silver sphere submerged in rain or river water in a silver or glass container in the North-West zone to fortify Chandra and calm Rahu mental affliction.',
    category: 'Remedy Canon',
    tags: ['Remedy', 'Silver', 'Water', 'Chandra', 'Rahu', 'North-West', 'Peace'],
    metadata: {
      targetPlanet: 'Chandra',
      rectifiesDefect: 'Chandra-Rahu Affliction / Anxiety / NW Water Defect',
      materialRequired: '40g Pure 999 Silver Sphere (Solid without hole)',
      placementZone: 'North-West / Near Water Filter'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    associatedDirection: 'North-West',
    associatedMetal: 'Solid Silver',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 12 - Chandra Rahu Upay',
      pageNumber: 412,
      paragraph: 'Para 1, Verse 15',
      ocrConfidence: 0.98,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 98,
      evidenceStrength: 96,
      knowledgeWeight: 0.96,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical remedy documentation']
  },
  {
    id: 'lk-rmd-002',
    canonicalName: 'Copper Coin Flow in River (Tambe Ka Sikka Jal Pravah)',
    alternateNames: ['Copper Coin Flow', 'Tambe Ka Paisa', 'Flowing Copper in River'],
    hindiName: 'तांबे का सिक्का जल प्रवाह (Tambe Sikka)',
    englishName: 'Flowing Unpunctured Copper Coin in Running Water',
    urduName: 'تانبے کا سکہ (Tambe Ka Sikka)',
    entityType: 'Remedy',
    description: 'Flowing 43 unpunctured square copper coins in natural running water continuously for 43 days to rectify Surya-Shani oppositions or government penalties.',
    category: 'Remedy Canon',
    tags: ['Remedy', 'Copper', 'Surya', 'Shani', 'River', '43 Days'],
    metadata: {
      targetPlanet: 'Surya',
      rectifiesDefect: 'Surya-Shani Conflict / Legal Disputes / Authority Friction',
      materialRequired: '43 Pure Square Copper Coins (Without hole)',
      method: 'Flow 1 coin daily in running river for 43 consecutive days'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    associatedMetal: 'Copper',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman 14 - Surya Shani Upay',
      pageNumber: 428,
      paragraph: 'Para 3, Verse 20',
      ocrConfidence: 0.97,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 97,
      evidenceStrength: 95,
      knowledgeWeight: 0.95,
      confidenceScore: 97,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical remedy documentation']
  },

  // ----------------------------------------------------
  // OBJECTS & METALS
  // ----------------------------------------------------
  {
    id: 'lk-obj-001',
    canonicalName: 'Solid Silver Block (Chandi Ka Chauras Tukda)',
    alternateNames: ['Square Silver Piece', 'Chandi Tukda'],
    hindiName: 'चांदी का चौकोर टुकड़ा (Chandi Tukda)',
    englishName: 'Square Solid Silver Piece (12g - 40g)',
    entityType: 'Object',
    description: 'A pure square silver sheet held in pocket or buried under entrance threshold to fortify Chandra and neutralize Rahu negative vibrations.',
    category: 'Objects Canon',
    tags: ['Object', 'Silver', 'Square', 'Chandra', 'Protection'],
    metadata: {
      weightGram: 20,
      shape: 'Square / Rectangular',
      purityPercent: 99.9
    },
    version: '1.0.0',
    status: 'CANONICAL',
    associatedMetal: 'Solid Silver',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman Objects - Chandi',
      pageNumber: 502,
      paragraph: 'Para 1, Verse 3',
      ocrConfidence: 0.99,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 99,
      evidenceStrength: 98,
      knowledgeWeight: 0.98,
      confidenceScore: 99,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical object documentation']
  },
  {
    id: 'lk-obj-002',
    canonicalName: 'Brass Pot with Honey (Pital Ka Bartan Shehad Se Bhara)',
    alternateNames: ['Honey in Brass Jar', 'Pital Shehad Pot'],
    hindiName: 'पीतल का बर्तन शहद से भरा (Pital Shehad)',
    englishName: 'Brass Vessel filled with Pure Natural Honey',
    entityType: 'Object',
    description: 'Brass vessel filled with organic honey placed in North-East or South zone to harmonize Guru and Mangal elements.',
    category: 'Objects Canon',
    tags: ['Object', 'Brass', 'Honey', 'Guru', 'Mangal', 'North-East'],
    metadata: {
      metalType: 'Brass',
      contents: 'Pure Honey',
      zone: 'North-East / South'
    },
    version: '1.0.0',
    status: 'CANONICAL',
    associatedDirection: 'North-East',
    associatedMetal: 'Brass',
    sourceTraceability: {
      sourceBook: 'Lal Kitab 1952 Farman',
      edition: '5th Edition Master Translation',
      publicationYear: 1952,
      publisher: 'Giridhari Lal / IGNCA Critical Edition',
      language: 'Hindi',
      chapter: 'Farman Objects - Pital Shehad',
      pageNumber: 518,
      paragraph: 'Para 2, Verse 7',
      ocrConfidence: 0.98,
      importBatch: 'BATCH-2026-LK-001',
      importTimestamp: '2026-07-26T00:00:00Z',
      verificationStatus: 'CANONICAL'
    },
    truthEngineMetrics: {
      sourceReliability: 98,
      evidenceStrength: 96,
      knowledgeWeight: 0.96,
      confidenceScore: 98,
      confidenceGrade: 'A+',
      expertConsensusStatus: 'Approved',
      hasActiveConflict: false,
      isCanonical: true
    },
    createdTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedTimestamp: '2026-07-26T00:00:00Z',
    lastUpdatedBy: 'Acharya Reviewer Node',
    revisionNotes: ['Canonical object documentation']
  }
];

export const INITIAL_LALKITAB_RELATIONSHIPS: ILalKitabRelationship[] = [
  {
    id: 'lk-rel-001',
    sourceEntityId: 'lk-grh-001',
    targetEntityId: 'lk-bhv-001',
    relationshipType: 'RULES',
    description: 'Surya rules House 1 as Pakka Ghar and brings royal authority.',
    weight: 0.98,
    isConditional: false,
    sourceBook: 'Lal Kitab 1952 Farman',
    confidenceScore: 99
  },
  {
    id: 'lk-rel-002',
    sourceEntityId: 'lk-grh-002',
    targetEntityId: 'lk-bhv-004',
    relationshipType: 'RULES',
    description: 'Chandra rules House 4 as Pakka Ghar symbolizing mother and liquid wealth.',
    weight: 0.97,
    isConditional: false,
    sourceBook: 'Lal Kitab 1952 Farman',
    confidenceScore: 98
  },
  {
    id: 'lk-rel-003',
    sourceEntityId: 'lk-rmd-001',
    targetEntityId: 'lk-grh-002',
    relationshipType: 'ENHANCES',
    description: 'Solid Silver in Water significantly enhances Chandra peace and counteracts Rahu anxiety.',
    weight: 0.96,
    isConditional: true,
    conditionText: 'When Rahu afflicts Chandra or NW water is polluted',
    sourceBook: 'Lal Kitab 1952 Farman',
    confidenceScore: 97
  },
  {
    id: 'lk-rel-004',
    sourceEntityId: 'lk-rmd-002',
    targetEntityId: 'lk-grh-001',
    relationshipType: 'ENHANCES',
    description: 'Flowing square copper coins fortifies Surya authority against Saturn restrictions.',
    weight: 0.95,
    isConditional: true,
    conditionText: 'When Surya-Shani aspect or legal disputes arise',
    sourceBook: 'Lal Kitab 1952 Farman',
    confidenceScore: 96
  },
  {
    id: 'lk-rel-005',
    sourceEntityId: 'lk-grh-007',
    targetEntityId: 'lk-grh-001',
    relationshipType: 'CONTRADICTS',
    description: 'Shani and Surya share an inherent mutual enmity in planetary rules.',
    weight: 0.94,
    isConditional: false,
    sourceBook: 'Lal Kitab 1952 Farman',
    confidenceScore: 98
  }
];

export const INITIAL_LALKITAB_CONFLICTS: ILalKitabConflict[] = [
  {
    conflictId: 'lk-cnf-001',
    entityId: 'lk-grh-003',
    conflictType: 'Conditional Discrepancy',
    description: 'Distinction between Mangal Neek (benefic Mars) and Mangal Badd (malefic Mars) placement rules across 1942 Tarmeem vs 1952 Farman editions.',
    sourceA: 'Lal Kitab 1942 Tarmeem Edition',
    claimA: 'Mangal in 4th house is always Mangal Badd regardless of aspect.',
    sourceB: 'Lal Kitab 1952 Farman Edition',
    claimB: 'Mangal in 4th house acts as Mangal Neek if Guru or Surya is situated in 1st or 10th house.',
    severity: 'MEDIUM',
    status: 'CONTEXTUAL_SPLIT',
    resolutionNotes: 'Accepted contextual rule split based on Jupiter/Sun aspect presence in accordance with SME Acharya consensus.',
    resolvedBy: 'Acharya Board Lead',
    resolvedTimestamp: '2026-07-26T00:00:00Z'
  },
  {
    conflictId: 'lk-cnf-002',
    entityId: 'lk-grh-008',
    conflictType: 'Book vs Book',
    description: 'Lead wire placement in South-West toilet drain: 1939 Farman vs 1952 Edition.',
    sourceA: 'Lal Kitab 1939 Farman',
    claimA: 'Burial of solid lead rod at SW corner.',
    sourceB: 'Lal Kitab 1952 Farman',
    claimB: 'Flowing raw lead pieces in sewer water on Saturday morning.',
    severity: 'HIGH',
    status: 'RESOLVED_CANONICAL',
    resolutionNotes: '1952 Farman edition established as canonical standard for active water drains; lead rod retained as stationary option.',
    resolvedBy: 'Acharya Board Lead',
    resolvedTimestamp: '2026-07-26T00:00:00Z'
  }
];

export const INITIAL_LALKITAB_DUPLICATES: ILalKitabDuplicateMatch[] = [
  {
    matchId: 'lk-dup-001',
    primaryEntityId: 'lk-obj-001',
    candidateEntityId: 'lk-obj-001-alt',
    similarityScore: 92,
    matchingAttributes: ['canonicalName', 'associatedMetal', 'tags'],
    status: 'PENDING_REVIEW'
  }
];
