export const CORE_CONSTANTS = {
  VERSION: '1.0.0',
  DEFAULT_GRID_SIZE: 20,
  DEFAULT_SNAP_THRESHOLD: 10,
  MAX_ZOOM: 5.0,
  MIN_ZOOM: 0.1,
  CANVAS_BG_COLOR: '#0a0f1c' // Based on slate-900 / slate-950 UI themes
};

export const EVENT_TYPES = {
  ENGINE_INITIALIZED: 'ENGINE_INITIALIZED',
  ENGINE_ERROR: 'ENGINE_ERROR',
  PROJECT_LOADED: 'PROJECT_LOADED',
  PROJECT_SAVED: 'PROJECT_SAVED'
};
