// src/components/lalkitab/YogasPanel.tsx
import React from "react";
import { LalKitabResult } from "./lalkitabEngine";
import { Award, ShieldAlert, Sparkles, AlertCircle } from "lucide-react";

interface YogasPanelProps {
  result: LalKitabResult | null;
}

export default function YogasPanel({ result }: YogasPanelProps) {
  if (!result) return null;

  const presentYogas = result.yogas.filter((y) => y.present);
  const inactiveYogas = result.yogas.filter((y) => !y.present);

  return (
    <div className="p-5 bg-slate-50 border border-slate-200 rounded-xl space-y-4 shadow-xl">
      <div className="border-b border-slate-200 pb-3 flex justify-between items-center">
        <div>
          <h4 className="text-xs font-mono font-bold text-slate-200 uppercase tracking-widest flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-emerald-400" />
            Lal Kitab & Vedic Planetary Yogas
          </h4>
          <p className="text-[10px] text-slate-400 font-mono mt-0.5">
            Beneficial astrological configurations generated by the interaction of houses and planets.
          </p>
        </div>
        <span className="text-[9px] font-mono font-bold bg-emerald-950 text-emerald-400 border border-emerald-900 px-2 py-0.5 rounded uppercase">
          {presentYogas.length} ACTIVE YOGAS FOUND
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-xs">
        {/* Present Yogas column */}
        <div className="space-y-3">
          <span className="text-[9px] text-slate-400 uppercase font-bold block">Present Active Formations</span>
          
          <div className="space-y-2.5">
            {presentYogas.map((yoga) => (
              <div 
                key={yoga.name} 
                className="p-3.5 bg-white/30 border border-emerald-900/40 rounded-lg space-y-2"
              >
                <div className="flex justify-between items-center border-b border-slate-950 pb-1.5">
                  <span className="font-bold text-emerald-400 text-xs uppercase tracking-wide">
                    {yoga.name}
                  </span>
                  <span className="text-[8px] bg-emerald-950/40 text-emerald-400 border border-emerald-900/30 px-2 py-0.5 rounded font-bold uppercase">
                    ACTIVE
                  </span>
                </div>
                <p className="text-slate-700 text-[11px] leading-relaxed">
                  {yoga.description}
                </p>
                <div className="text-[10px] text-slate-400 leading-tight">
                  <strong className="text-slate-400">Manifestation:</strong> {yoga.effects}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Inactive Yogas column */}
        <div className="space-y-3">
          <span className="text-[9px] text-slate-400 uppercase font-bold block">Inactive Formations (Dormant)</span>

          <div className="space-y-2.5 opacity-60">
            {inactiveYogas.map((yoga) => (
              <div 
                key={yoga.name} 
                className="p-3 bg-white/20 border border-slate-200 rounded-lg space-y-1"
              >
                <div className="flex justify-between items-center text-[11px]">
                  <span className="font-bold text-slate-400 uppercase">
                    {yoga.name}
                  </span>
                  <span className="text-[8px] bg-slate-50 text-slate-600 border border-slate-200 px-1.5 py-0.5 rounded font-bold uppercase">
                    Dormant
                  </span>
                </div>
                <p className="text-[10px] text-slate-400 leading-tight">
                  {yoga.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
