/**
 * KIE Sprint-2 Module 1: Client Discovery Engine Types (Founder Edition)
 * Follows the Frozen KIE Architecture for Human Consultant Discovery.
 */

export type ExpandedPropertyCategory = 
  | "Apartment"
  | "Independent House"
  | "Villa"
  | "Duplex"
  | "Farm House"
  | "Shop"
  | "Office"
  | "Commercial Office"
  | "Factory"
  | "Warehouse"
  | "Industrial Unit"
  | "Clinic"
  | "Hospital"
  | "Hotel"
  | "Restaurant"
  | "School"
  | "College"
  | "Temple"
  | "Plot"
  | "Mixed Use Property"
  | "Other";

// Legacy property types mapped for backwards compatibility
export type PropertyType = "Residential" | "Commercial" | "Plot" | "Other";
export type PropertySubType = string;

export type PropertyOwnership = 
  | "Self Owned"
  | "Rented"
  | "Under Construction"
  | "Renovation";

export type ConsultationPurpose = 
  | "Financial Growth"
  | "Debt Problems"
  | "Business Expansion"
  | "Career Growth"
  | "Health"
  | "Family Harmony"
  | "Marriage"
  | "Children's Education"
  | "Mental Peace"
  | "Legal Matters"
  | "Property Purchase"
  | "New Construction"
  | "Other";

export interface OccupantsInfo {
  totalMembers: number;
  adults: number;
  children: number;
  seniorCitizens: number;
  workingProfessionals: number;
  students: number;
}

export type PropertyConstraint = 
  | "No Demolition"
  | "Low Budget"
  | "Moderate Budget"
  | "Premium Budget"
  | "Society Restrictions"
  | "Rental Restrictions"
  | "Structural Changes Allowed";

export type ClientPreference = 
  | "Only Practical Remedies"
  | "Traditional Remedies Accepted"
  | "Non-Invasive Remedies Only"
  | "Structural Remedies Allowed"
  | "White Label Consultant Report Required";

export type ReportLanguage = 
  | "English"
  | "Hindi"
  | "Hinglish"
  | "Marathi"
  | "Gujarati"
  | "Punjabi"
  | "Tamil"
  | "Telugu"
  | "Bengali"
  | "Other";

export type ReportTypePreference = 
  | "Homeowner Report"
  | "Professional Consultant Report"
  | "White Label Report"
  | "Founder Review Report";

export interface ClientInfo {
  clientName: string;
  mobile: string;
  email: string;
  city: string;
  country: string;
}

export interface ClientDiscoveryRecord {
  // Automatic Identity (Generated by Engine)
  clientId: string;
  consultationId: string;
  discoveryId: string;
  timestamp: number;
  isCompleted: boolean;
  
  // SECTION 1: Client Information
  clientInfo: ClientInfo;

  // SECTION 2: Expanded Property Category
  propertyCategory: ExpandedPropertyCategory;
  propertyType: PropertyType; // Derived / Backwards compatible
  propertySubType: PropertySubType; // Derived / Backwards compatible

  // SECTION 3: Property Ownership
  propertyOwnership: PropertyOwnership;

  // SECTION 4: Primary Consultation Purpose
  primaryPurposes: ConsultationPurpose[];

  // SECTION 5: Client Goal
  clientGoal: string;

  // SECTION 6: People Living in the Property
  occupants: OccupantsInfo;

  // SECTION 7: Property Constraints
  constraints: PropertyConstraint[];

  // SECTION 8: Client Preferences
  preferences: ClientPreference[];

  // NEW SECTION: Preferred Report Language
  preferredLanguage: ReportLanguage;

  // NEW SECTION: Preferred Report Type
  preferredReportType: ReportTypePreference;

  // SECTION 9: Additional Notes
  additionalNotes: string;

  // Automatically prepared summary for downstream KIE modules
  summary?: DiscoverySummary;
}

export interface DiscoverySummary {
  clientId: string;
  consultationId: string;
  clientName: string;
  cityAndCountry: string;
  propertyCategory: ExpandedPropertyCategory;
  ownership: PropertyOwnership;
  primaryProblems: ConsultationPurpose[];
  primaryGoals: string;
  familySummary: {
    totalMembers: number;
    breakdownText: string;
  };
  propertyConstraints: PropertyConstraint[];
  clientPreferences: ClientPreference[];
  preferredLanguage: ReportLanguage;
  preferredReportType: ReportTypePreference;
  additionalNotes: string;
  generatedAtFormatted: string;
}

export interface ClientDiscoveryValidationResult {
  isValid: boolean;
  completedSectionsCount: number;
  totalSectionsCount: number;
  errors: Record<string, string>;
  summary?: DiscoverySummary;
}

/**
 * Provider-Independent Storage Interface for Client Discovery
 * Enables zero-code switching between Local Storage, Firebase, Supabase, Cloud DB, etc.
 */
export interface IClientDiscoveryStorageProvider {
  saveDiscovery(record: ClientDiscoveryRecord): Promise<void> | void;
  loadDiscovery(): Promise<ClientDiscoveryRecord | null> | ClientDiscoveryRecord | null;
  clearDiscovery(): Promise<void> | void;
  getProviderName(): string;
}

